squid:
  hostname: squid
  container_name: squid
  image: dr4g0nsr/docker-squid:latest
  environment:
    - TRAFFIC_LIMIT="yes"
    - TRAFFIC_DOWNLOAD_UPLOAD="2000 2000" # KB/sec
    - SQUID_LIMIT="yes" # Elite proxy settings
    - SQUID_DOWNLOAD_UPLOAD="1000 1000"
    - ELITE_PROXY="yes" # Elite proxy settings
    - CACHE_MANAGER="yes"
  ports:
    - "3128:3128/tcp"
    - "800:80/tcp"
  volumes:
    - ./data/squid/cache:/var/spool/squid
    - ./squid.conf:/etc/squid/squid.conf
    - ./data/squid/log:/var/log/squid
  deploy:
    resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M
  restart: always
